<?php

namespace Database\Seeders;

use App\Models\SeoLead;
use App\Models\SeoLeadCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LeadGenSeeder extends Seeder
{
    public function run(): void
    {
        $categories = $this->getCategories();
        $leads = $this->getLeads();

        foreach ($categories as $cat) {
            SeoLeadCategory::updateOrInsert(['id' => $cat['id']], $cat);
        }

        foreach ($leads as $lead) {
            SeoLead::updateOrInsert(['id' => $lead['id']], $lead);
        }

        if (DB::getDriverName() === 'mysql') {
            $maxId = SeoLead::max('id') ?? 0;
            DB::statement("ALTER TABLE seo_leads AUTO_INCREMENT = " . ($maxId + 1));
        }

        $this->command->info("LeadGenSeeder: " . SeoLead::count() . " leads, " . SeoLeadCategory::count() . " categories");
    }

    private function getCategories(): array
    {
        return [
            ['id' => 1, 'category_name' => 'General', 'keywords' => 'business, services', 'location' => 'Bahrain', 'platforms' => '["google_maps","google_search"]', 'max_leads' => 100, 'priority' => 1, 'auto_enrich' => 0, 'min_score_threshold' => 0, 'target_audience' => null, 'notes' => null, 'is_active' => 1, 'created_at' => '2026-06-15 14:15:06', 'updated_at' => '2026-06-15 14:15:06'],
            ['id' => 2, 'category_name' => 'Service', 'keywords' => 'SEO, GEO, AEO, digital marketing, AI search, web development, content writing, social media', 'location' => 'Bahrain', 'platforms' => '["google_maps","google_search","instagram","facebook"]', 'max_leads' => 200, 'priority' => 2, 'auto_enrich' => 1, 'min_score_threshold' => 30, 'target_audience' => 'Businesses looking for SEO, GEO, AEO, and digital marketing services in Bahrain', 'notes' => null, 'is_active' => 1, 'created_at' => '2026-06-15 14:16:38', 'updated_at' => '2026-06-15 14:16:38'],
            ['id' => 3, 'category_name' => 'Custom', 'keywords' => null, 'location' => null, 'platforms' => '["google_maps"]', 'max_leads' => 50, 'priority' => 3, 'auto_enrich' => 0, 'min_score_threshold' => 0, 'target_audience' => null, 'notes' => null, 'is_active' => 1, 'created_at' => '2026-06-15 14:19:05', 'updated_at' => '2026-06-15 14:19:05'],
            ['id' => 4, 'category_name' => 'Cleaning Services', 'keywords' => 'cleaning services, house cleaning, office cleaning, janitorial, deep cleaning, commercial cleaning, residential cleaning, carpet cleaning', 'location' => 'Bahrain', 'platforms' => '["google_maps","instagram","facebook"]', 'max_leads' => 50, 'priority' => 5, 'auto_enrich' => 1, 'min_score_threshold' => 0, 'target_audience' => 'Homeowners, property managers, businesses, offices in Bahrain needing professional cleaning services', 'notes' => null, 'is_active' => 1, 'created_at' => '2026-06-21 06:04:04', 'updated_at' => '2026-06-21 06:04:04'],
        ];
    }

    private function getLeads(): array
    {
        return [
            ['id' => 1, 'source' => 'manual', 'business_name' => 'Al Baraka Banking Group', 'contact_person' => 'Ahmed Al Khalifa', 'email' => 'ahmed@albaraka.com.bh', 'phone' => '+973 1711 1111', 'website' => 'https://www.albaraka.com', 'address' => 'Road 383, Block 316, Building 777, Manama', 'city' => 'Manama', 'country' => 'Bahrain', 'category' => null, 'social_instagram' => null, 'social_facebook' => null, 'rating' => null, 'reviews_count' => 0, 'lead_score' => 75, 'status' => 'new', 'notes' => null, 'category_id' => null, 'created_at' => '2026-06-15 14:12:38', 'updated_at' => '2026-06-15 14:12:38', 'lead_type' => 'customer', 'social_tiktok' => null, 'social_youtube' => null, 'social_linkedin' => null, 'social_twitter' => null, 'platform_profile_name' => null, 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => null, 'whatsapp_phone' => '+973 1711 1111'],
            ['id' => 2, 'source' => 'manual', 'business_name' => 'Bahrain International Airport Services', 'contact_person' => 'Khalid Al Zayani', 'email' => 'khalid@bias.com.bh', 'phone' => '+973 1735 9999', 'website' => 'https://www.bahrainairport.com', 'address' => 'Muharraq Highway, Muharraq', 'city' => 'Muharraq', 'country' => 'Bahrain', 'category' => null, 'social_instagram' => null, 'social_facebook' => null, 'rating' => null, 'reviews_count' => 0, 'lead_score' => 60, 'status' => 'contacted', 'notes' => null, 'category_id' => null, 'created_at' => '2026-06-15 14:12:38', 'updated_at' => '2026-06-15 14:12:38', 'lead_type' => 'customer', 'social_tiktok' => null, 'social_youtube' => null, 'social_linkedin' => null, 'social_twitter' => null, 'platform_profile_name' => null, 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => null, 'whatsapp_phone' => '+973 1735 9999'],
            ['id' => 3, 'source' => 'manual', 'business_name' => 'Gulf Tech Solutions WLL', 'contact_person' => 'Sara Al Mahmood', 'email' => 'sara@gulftech.com.bh', 'phone' => '+973 1722 3333', 'website' => 'https://www.gulftech.com.bh', 'address' => 'Building 456, Road 284, Seef District', 'city' => 'Seef', 'country' => 'Bahrain', 'category' => null, 'social_instagram' => null, 'social_facebook' => null, 'rating' => null, 'reviews_count' => 0, 'lead_score' => 85, 'status' => 'qualified', 'notes' => null, 'category_id' => null, 'created_at' => '2026-06-15 14:12:38', 'updated_at' => '2026-06-15 14:12:38', 'lead_type' => 'provider', 'social_tiktok' => null, 'social_youtube' => null, 'social_linkedin' => null, 'social_twitter' => null, 'platform_profile_name' => null, 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => null, 'whatsapp_phone' => '+973 1722 3333'],
            ['id' => 4, 'source' => 'manual', 'business_name' => 'Royal Riffa Palace Hotel', 'contact_person' => 'Nasser Al Arrayed', 'email' => 'nasser@royalriffa.com', 'phone' => '+973 1758 8888', 'website' => 'https://www.royalriffa.com', 'address' => 'Riffa High Street, Riffa', 'city' => 'Riffa', 'country' => 'Bahrain', 'category' => null, 'social_instagram' => null, 'social_facebook' => null, 'rating' => null, 'reviews_count' => 0, 'lead_score' => 90, 'status' => 'converted', 'notes' => null, 'category_id' => null, 'created_at' => '2026-06-15 14:12:38', 'updated_at' => '2026-06-15 14:12:38', 'lead_type' => 'customer', 'social_tiktok' => null, 'social_youtube' => null, 'social_linkedin' => null, 'social_twitter' => null, 'platform_profile_name' => null, 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => null, 'whatsapp_phone' => '+973 1758 8888'],
            ['id' => 5, 'source' => 'manual', 'business_name' => 'Digital Marketing Pro Agency', 'contact_person' => 'Layla Al Jassim', 'email' => 'layla@dmpro.com.bh', 'phone' => '+973 1766 2222', 'website' => 'https://www.dmpro.com.bh', 'address' => 'Office 12, Bahrain Financial Harbour', 'city' => 'Manama', 'country' => 'Bahrain', 'category' => null, 'social_instagram' => null, 'social_facebook' => null, 'rating' => null, 'reviews_count' => 0, 'lead_score' => 45, 'status' => 'new', 'notes' => null, 'category_id' => null, 'created_at' => '2026-06-15 14:12:38', 'updated_at' => '2026-06-15 14:12:38', 'lead_type' => 'provider', 'social_tiktok' => null, 'social_youtube' => null, 'social_linkedin' => null, 'social_twitter' => null, 'platform_profile_name' => null, 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => null, 'whatsapp_phone' => '+973 1766 2222'],
            ['id' => 25, 'source' => 'ai_generated', 'business_name' => 'Test Solutions Bahrain W.L.L.', 'contact_person' => 'Ahmed Al Khalifa', 'email' => 'a.alkhalifa@testsolutionsbh.com', 'phone' => '+973 1712 3456', 'website' => 'https://testsolutionsbh.com', 'address' => 'Building 245, Road 3819, Block 338', 'city' => 'Manama', 'country' => 'Bahrain', 'category' => '', 'social_instagram' => '', 'social_facebook' => '', 'rating' => 4.3, 'reviews_count' => 28, 'lead_score' => 82, 'status' => 'new', 'notes' => '{"ai_generated":true,"keyword":"test"}', 'category_id' => null, 'created_at' => '2026-06-21 05:48:45', 'updated_at' => '2026-06-21 05:48:45', 'lead_type' => 'provider', 'social_tiktok' => '', 'social_youtube' => '', 'social_linkedin' => '', 'social_twitter' => '', 'platform_profile_name' => '', 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => '', 'whatsapp_phone' => null],
            ['id' => 26, 'source' => 'ai_generated', 'business_name' => 'AccuTest Laboratories', 'contact_person' => 'Sara Al Jishi', 'email' => 's.aljishi@accutest.com.bh', 'phone' => '+973 3940 1122', 'website' => 'https://accutest.com.bh', 'address' => 'Building 12, Road 100, Block 140', 'city' => 'Riffa', 'country' => 'Bahrain', 'category' => '', 'social_instagram' => '', 'social_facebook' => '', 'rating' => 4.7, 'reviews_count' => 45, 'lead_score' => 91, 'status' => 'new', 'notes' => '{"ai_generated":true,"keyword":"test"}', 'category_id' => null, 'created_at' => '2026-06-21 05:48:45', 'updated_at' => '2026-06-21 05:48:45', 'lead_type' => 'provider', 'social_tiktok' => '', 'social_youtube' => '', 'social_linkedin' => '', 'social_twitter' => '', 'platform_profile_name' => '', 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => '', 'whatsapp_phone' => null],
            ['id' => 27, 'source' => 'ai_generated', 'business_name' => 'PrimeTest Engineering Services', 'contact_person' => 'Hassan Al Ansari', 'email' => 'h.ansari@primetest.bh', 'phone' => '+973 3612 9988', 'website' => 'https://primetest.bh', 'address' => 'Office 5, Al Jazeera Tower, Government Avenue', 'city' => 'Muharraq', 'country' => 'Bahrain', 'category' => '', 'social_instagram' => '', 'social_facebook' => '', 'rating' => 3.9, 'reviews_count' => 17, 'lead_score' => 65, 'status' => 'new', 'notes' => '{"ai_generated":true,"keyword":"test"}', 'category_id' => null, 'created_at' => '2026-06-21 05:48:45', 'updated_at' => '2026-06-21 05:48:45', 'lead_type' => 'provider', 'social_tiktok' => '', 'social_youtube' => '', 'social_linkedin' => '', 'social_twitter' => '', 'platform_profile_name' => '', 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => '', 'whatsapp_phone' => null],
            ['id' => 28, 'source' => 'ai_generated', 'business_name' => 'GlobalTest Bahrain Co.', 'contact_person' => 'Layla Al Qassab', 'email' => 'l.qassab@globaltestbh.net', 'phone' => '+973 1777 6565', 'website' => 'https://globaltestbh.net', 'address' => 'Building 67, Road 2002, Block 220', 'city' => 'Seef', 'country' => 'Bahrain', 'category' => '', 'social_instagram' => '', 'social_facebook' => '', 'rating' => 4.1, 'reviews_count' => 33, 'lead_score' => 78, 'status' => 'new', 'notes' => '{"ai_generated":true,"keyword":"test"}', 'category_id' => null, 'created_at' => '2026-06-21 05:48:45', 'updated_at' => '2026-06-21 05:48:45', 'lead_type' => 'provider', 'social_tiktok' => '', 'social_youtube' => '', 'social_linkedin' => '', 'social_twitter' => '', 'platform_profile_name' => '', 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => '', 'whatsapp_phone' => null],
            ['id' => 29, 'source' => 'ai_generated', 'business_name' => 'TestMaster Inspection Labs', 'contact_person' => 'Yusuf Al Mannai', 'email' => 'y.mannai@testmasterlabs.com', 'phone' => '+973 3330 4477', 'website' => 'https://testmasterlabs.com', 'address' => 'Warehouse 8, Hidd Industrial Area, Road 5000', 'city' => 'Hidd', 'country' => 'Bahrain', 'category' => '', 'social_instagram' => '', 'social_facebook' => '', 'rating' => 4.5, 'reviews_count' => 52, 'lead_score' => 87, 'status' => 'new', 'notes' => '{"ai_generated":true,"keyword":"test"}', 'category_id' => null, 'created_at' => '2026-06-21 05:48:45', 'updated_at' => '2026-06-21 05:48:45', 'lead_type' => 'provider', 'social_tiktok' => '', 'social_youtube' => '', 'social_linkedin' => '', 'social_twitter' => '', 'platform_profile_name' => '', 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => '', 'whatsapp_phone' => null],
            ['id' => 30, 'source' => 'manual', 'business_name' => 'Sparkle Clean Bahrain', 'contact_person' => 'Ahmed Al Khalifa', 'email' => 'info@sparklecleanbh.com', 'phone' => '+973 3991 2345', 'website' => 'https://sparklecleanbh.com', 'address' => null, 'city' => 'Manama', 'country' => 'Bahrain', 'category' => null, 'social_instagram' => null, 'social_facebook' => null, 'rating' => 4.5, 'reviews_count' => 47, 'lead_score' => 85, 'status' => 'new', 'notes' => '{"imported":true,"seeded_at":"2026-06-21 06:04:04"}', 'category_id' => 4, 'created_at' => '2026-06-21 06:04:04', 'updated_at' => '2026-06-21 06:04:04', 'lead_type' => 'provider', 'social_tiktok' => null, 'social_youtube' => null, 'social_linkedin' => null, 'social_twitter' => null, 'platform_profile_name' => null, 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => null, 'whatsapp_phone' => '+973 3991 2345'],
            ['id' => 31, 'source' => 'manual', 'business_name' => 'Al Manar Cleaning Services', 'contact_person' => 'Fatima Hasan', 'email' => 'info@almanarcleaning.com', 'phone' => '+973 3654 7890', 'website' => 'https://almanarcleaning.com', 'address' => null, 'city' => 'Muharraq', 'country' => 'Bahrain', 'category' => null, 'social_instagram' => null, 'social_facebook' => null, 'rating' => 4.2, 'reviews_count' => 23, 'lead_score' => 72, 'status' => 'new', 'notes' => '{"imported":true,"seeded_at":"2026-06-21 06:04:04"}', 'category_id' => 4, 'created_at' => '2026-06-21 06:04:04', 'updated_at' => '2026-06-21 06:04:04', 'lead_type' => 'provider', 'social_tiktok' => null, 'social_youtube' => null, 'social_linkedin' => null, 'social_twitter' => null, 'platform_profile_name' => null, 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => null, 'whatsapp_phone' => null],
            ['id' => 32, 'source' => 'manual', 'business_name' => 'Gulf Genie Cleaning', 'contact_person' => 'Khalid Al Jazeeri', 'email' => 'hello@gulfgeniebh.com', 'phone' => '+973 3440 5566', 'website' => 'https://gulfgeniebh.com', 'address' => null, 'city' => 'Riffa', 'country' => 'Bahrain', 'category' => null, 'social_instagram' => null, 'social_facebook' => null, 'rating' => 4.8, 'reviews_count' => 112, 'lead_score' => 90, 'status' => 'new', 'notes' => '{"imported":true,"seeded_at":"2026-06-21 06:04:05"}', 'category_id' => 4, 'created_at' => '2026-06-21 06:04:05', 'updated_at' => '2026-06-21 06:04:05', 'lead_type' => 'provider', 'social_tiktok' => null, 'social_youtube' => null, 'social_linkedin' => null, 'social_twitter' => null, 'platform_profile_name' => null, 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => null, 'whatsapp_phone' => null],
            ['id' => 33, 'source' => 'manual', 'business_name' => 'CleanPro Bahrain', 'contact_person' => 'Noora Al Saad', 'email' => 'info@cleanpro.com.bh', 'phone' => '+973 1733 5678', 'website' => 'https://cleanpro.com.bh', 'address' => null, 'city' => 'Manama', 'country' => 'Bahrain', 'category' => null, 'social_instagram' => null, 'social_facebook' => null, 'rating' => 3.9, 'reviews_count' => 15, 'lead_score' => 65, 'status' => 'new', 'notes' => '{"imported":true,"seeded_at":"2026-06-21 06:04:05"}', 'category_id' => 4, 'created_at' => '2026-06-21 06:04:05', 'updated_at' => '2026-06-21 06:04:05', 'lead_type' => 'provider', 'social_tiktok' => null, 'social_youtube' => null, 'social_linkedin' => null, 'social_twitter' => null, 'platform_profile_name' => null, 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => null, 'whatsapp_phone' => null],
            ['id' => 34, 'source' => 'manual', 'business_name' => 'EcoClean Bahrain', 'contact_person' => 'Hassan Al Ansari', 'email' => 'contact@ecocleanbh.net', 'phone' => '+973 3612 8901', 'website' => 'https://ecocleanbh.net', 'address' => null, 'city' => 'Hamad Town', 'country' => 'Bahrain', 'category' => null, 'social_instagram' => null, 'social_facebook' => null, 'rating' => 4.3, 'reviews_count' => 34, 'lead_score' => 78, 'status' => 'new', 'notes' => '{"imported":true,"seeded_at":"2026-06-21 06:04:05"}', 'category_id' => 4, 'created_at' => '2026-06-21 06:04:05', 'updated_at' => '2026-06-21 06:04:05', 'lead_type' => 'provider', 'social_tiktok' => null, 'social_youtube' => null, 'social_linkedin' => null, 'social_twitter' => null, 'platform_profile_name' => null, 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => null, 'whatsapp_phone' => null],
            ['id' => 35, 'source' => 'manual', 'business_name' => 'ProShine Cleaning WLL', 'contact_person' => 'Layla Al Qassab', 'email' => 'info@proshinebh.com', 'phone' => '+973 3990 1122', 'website' => 'https://proshinebh.com', 'address' => null, 'city' => 'Manama', 'country' => 'Bahrain', 'category' => null, 'social_instagram' => null, 'social_facebook' => null, 'rating' => 4.6, 'reviews_count' => 78, 'lead_score' => 88, 'status' => 'new', 'notes' => '{"imported":true,"seeded_at":"2026-06-21 06:04:05"}', 'category_id' => 4, 'created_at' => '2026-06-21 06:04:05', 'updated_at' => '2026-06-21 06:04:05', 'lead_type' => 'provider', 'social_tiktok' => null, 'social_youtube' => null, 'social_linkedin' => null, 'social_twitter' => null, 'platform_profile_name' => null, 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => null, 'whatsapp_phone' => '+973 3990 1122'],
            ['id' => 36, 'source' => 'manual', 'business_name' => 'Crystal Clear Cleaning', 'contact_person' => 'Yusuf Al Mannai', 'email' => 'info@crystalclearbh.com', 'phone' => '+973 3665 7788', 'website' => 'https://crystalclearbh.com', 'address' => null, 'city' => 'Isa Town', 'country' => 'Bahrain', 'category' => null, 'social_instagram' => null, 'social_facebook' => null, 'rating' => 3.7, 'reviews_count' => 9, 'lead_score' => 55, 'status' => 'new', 'notes' => '{"imported":true,"seeded_at":"2026-06-21 06:04:05"}', 'category_id' => 4, 'created_at' => '2026-06-21 06:04:05', 'updated_at' => '2026-06-21 06:04:05', 'lead_type' => 'provider', 'social_tiktok' => null, 'social_youtube' => null, 'social_linkedin' => null, 'social_twitter' => null, 'platform_profile_name' => null, 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => null, 'whatsapp_phone' => null],
            ['id' => 37, 'source' => 'manual', 'business_name' => 'Al Jazira Cleaning', 'contact_person' => 'Mariam Al Bin Ali', 'email' => 'info@aljazira-cleaning.com', 'phone' => '+973 1712 3456', 'website' => 'https://aljazira-cleaning.com', 'address' => null, 'city' => 'Sitra', 'country' => 'Bahrain', 'category' => null, 'social_instagram' => null, 'social_facebook' => null, 'rating' => 4, 'reviews_count' => 28, 'lead_score' => 70, 'status' => 'new', 'notes' => '{"imported":true,"seeded_at":"2026-06-21 06:04:06"}', 'category_id' => 4, 'created_at' => '2026-06-21 06:04:06', 'updated_at' => '2026-06-21 06:04:06', 'lead_type' => 'provider', 'social_tiktok' => null, 'social_youtube' => null, 'social_linkedin' => null, 'social_twitter' => null, 'platform_profile_name' => null, 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => null, 'whatsapp_phone' => '+973 1712 3456'],
            ['id' => 38, 'source' => 'ai_generated', 'business_name' => 'Sparkle Clean Co. W.L.L.', 'contact_person' => 'Ahmed Al-Jowder', 'email' => 'ahmed@sparklecleaning.bh', 'phone' => '+973 1723 4567', 'website' => 'www.sparklecleaning.bh', 'address' => 'Building 245, Road 422, Block 304', 'city' => 'Manama', 'country' => 'Bahrain', 'category' => '', 'social_instagram' => '', 'social_facebook' => '', 'rating' => 4.5, 'reviews_count' => 82, 'lead_score' => 85, 'status' => 'new', 'notes' => '{"ai_generated":true,"keyword":"cleaning"}', 'category_id' => null, 'created_at' => '2026-06-21 06:07:28', 'updated_at' => '2026-06-21 06:07:28', 'lead_type' => 'provider', 'social_tiktok' => '', 'social_youtube' => '', 'social_linkedin' => '', 'social_twitter' => '', 'platform_profile_name' => '', 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => '', 'whatsapp_phone' => null],
            ['id' => 39, 'source' => 'ai_generated', 'business_name' => 'Al-Reef Services Cleaning', 'contact_person' => 'Hassan Al-Mutairi', 'email' => 'hassan.mutairi@alreefservices.com', 'phone' => '+973 3940 1122', 'website' => 'www.alreefservices.com', 'address' => 'Shop 12, Al-Muharraq Avenue, Block 222', 'city' => 'Muharraq', 'country' => 'Bahrain', 'category' => '', 'social_instagram' => '', 'social_facebook' => '', 'rating' => 4, 'reviews_count' => 45, 'lead_score' => 72, 'status' => 'new', 'notes' => '{"ai_generated":true,"keyword":"cleaning"}', 'category_id' => null, 'created_at' => '2026-06-21 06:07:28', 'updated_at' => '2026-06-21 06:07:28', 'lead_type' => 'provider', 'social_tiktok' => '', 'social_youtube' => '', 'social_linkedin' => '', 'social_twitter' => '', 'platform_profile_name' => '', 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => '', 'whatsapp_phone' => null],
            ['id' => 40, 'source' => 'ai_generated', 'business_name' => 'Gulf Pearl Cleaning Services', 'contact_person' => 'Layla Al-Khalifa', 'email' => 'info@gulfpearlcleaning.bh', 'phone' => '+973 3650 8899', 'website' => 'www.gulfpearlcleaning.bh', 'address' => 'Building 1010, Road 120, Block 601', 'city' => 'Riffa', 'country' => 'Bahrain', 'category' => '', 'social_instagram' => '', 'social_facebook' => '', 'rating' => 4.7, 'reviews_count' => 110, 'lead_score' => 91, 'status' => 'new', 'notes' => '{"ai_generated":true,"keyword":"cleaning"}', 'category_id' => null, 'created_at' => '2026-06-21 06:07:28', 'updated_at' => '2026-06-21 06:07:28', 'lead_type' => 'provider', 'social_tiktok' => '', 'social_youtube' => '', 'social_linkedin' => '', 'social_twitter' => '', 'platform_profile_name' => '', 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => '', 'whatsapp_phone' => null],
            ['id' => 41, 'source' => 'ai_generated', 'business_name' => 'Al Maha Cleaning Services', 'contact_person' => 'Hassan Al Jamea', 'email' => 'info@almahaclean.com.bh', 'phone' => '+973 3960 1234', 'website' => 'https://www.almahaclean.com.bh', 'address' => 'Building 45, Road 362, Block 336', 'city' => 'Manama', 'country' => 'Bahrain', 'category' => '', 'social_instagram' => '', 'social_facebook' => '', 'rating' => 4.5, 'reviews_count' => 127, 'lead_score' => 85, 'status' => 'new', 'notes' => '{"ai_generated":true,"keyword":"cleaning services"}', 'category_id' => null, 'created_at' => '2026-06-21 06:13:35', 'updated_at' => '2026-06-21 06:13:35', 'lead_type' => 'provider', 'social_tiktok' => '', 'social_youtube' => '', 'social_linkedin' => '', 'social_twitter' => '', 'platform_profile_name' => '', 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => '', 'whatsapp_phone' => null],
            ['id' => 42, 'source' => 'ai_generated', 'business_name' => 'Golden Shine Cleaning Co.', 'contact_person' => 'Layla Al Khalifa', 'email' => 'contact@goldenshinebh.com', 'phone' => '+973 3911 4587', 'website' => 'https://www.goldenshinebh.com', 'address' => 'Shop 12, Avenue 22, Block 409', 'city' => 'Muharraq', 'country' => 'Bahrain', 'category' => '', 'social_instagram' => '', 'social_facebook' => '', 'rating' => 4.8, 'reviews_count' => 203, 'lead_score' => 92, 'status' => 'new', 'notes' => '{"ai_generated":true,"keyword":"cleaning services"}', 'category_id' => null, 'created_at' => '2026-06-21 06:13:36', 'updated_at' => '2026-06-21 06:13:36', 'lead_type' => 'provider', 'social_tiktok' => '', 'social_youtube' => '', 'social_linkedin' => '', 'social_twitter' => '', 'platform_profile_name' => '', 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => '', 'whatsapp_phone' => null],
            ['id' => 43, 'source' => 'ai_generated', 'business_name' => 'CleanPro Bahrain', 'contact_person' => 'Ali Mansoor', 'email' => 'ali.mansoor@cleanprobh.net', 'phone' => '+973 3777 2345', 'website' => 'https://www.cleanprobh.net', 'address' => 'Office 7, Al Razi Complex, Building 1010', 'city' => 'Riffa', 'country' => 'Bahrain', 'category' => '', 'social_instagram' => '', 'social_facebook' => '', 'rating' => 4.2, 'reviews_count' => 89, 'lead_score' => 73, 'status' => 'new', 'notes' => '{"ai_generated":true,"keyword":"cleaning services"}', 'category_id' => null, 'created_at' => '2026-06-21 06:13:36', 'updated_at' => '2026-06-21 06:13:36', 'lead_type' => 'unknown', 'social_tiktok' => '', 'social_youtube' => '', 'social_linkedin' => '', 'social_twitter' => '', 'platform_profile_name' => '', 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => '', 'whatsapp_phone' => null],
            ['id' => 44, 'source' => 'ai_generated', 'business_name' => 'Sparkle & Fresh Cleaning', 'contact_person' => 'Nadia Hassan', 'email' => 'nadiah@sparklefresh.com.bh', 'phone' => '+973 3666 7890', 'website' => 'https://www.sparklefresh.com.bh', 'address' => 'Villa 8, Street 91, Block 538', 'city' => 'Juffair', 'country' => 'Bahrain', 'category' => '', 'social_instagram' => '', 'social_facebook' => '', 'rating' => 4, 'reviews_count' => 54, 'lead_score' => 68, 'status' => 'new', 'notes' => '{"ai_generated":true,"keyword":"cleaning services"}', 'category_id' => null, 'created_at' => '2026-06-21 06:13:36', 'updated_at' => '2026-06-21 06:13:36', 'lead_type' => 'unknown', 'social_tiktok' => '', 'social_youtube' => '', 'social_linkedin' => '', 'social_twitter' => '', 'platform_profile_name' => '', 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => '', 'whatsapp_phone' => null],
            ['id' => 45, 'source' => 'ai_generated', 'business_name' => 'EcoClean Bahrain', 'contact_person' => 'Yusuf Al Naser', 'email' => 'info@ecocleanbh.org', 'phone' => '+973 3830 6655', 'website' => 'https://www.ecocleanbh.org', 'address' => 'Unit 3, Commercial Center, Road 2404', 'city' => 'Saar', 'country' => 'Bahrain', 'category' => '', 'social_instagram' => '', 'social_facebook' => '', 'rating' => 4.6, 'reviews_count' => 78, 'lead_score' => 88, 'status' => 'new', 'notes' => '{"ai_generated":true,"keyword":"cleaning services"}', 'category_id' => null, 'created_at' => '2026-06-21 06:13:36', 'updated_at' => '2026-06-21 06:13:36', 'lead_type' => 'unknown', 'social_tiktok' => '', 'social_youtube' => '', 'social_linkedin' => '', 'social_twitter' => '', 'platform_profile_name' => '', 'followers_count' => 0, 'engagement_count' => 0, 'last_post_content' => '', 'whatsapp_phone' => null],
        ];
    }
}
