/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {},
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("daisyui"),
  ],
  daisyui: {
    themes: [
      "light",
      "dark",
      "night",
      "corporate",
      "ocean",
      "sunset",
      "forest",
      "midnight",
      "candy",
      "cyberpunk",
      "garden",
      "luxury",
      "coffee",
      "emerald",
      "royal",
      "autumn",
      "spring",
      "arctic",
      "lavender",
      "cherry",
      "neon",
      "pastel",
      "slate",
      "dracula",
      "dim",
      "nord",
      "business",
      "acid",
      "lemonade",
      "wireframe",
      "cmyk",
      "lofi",
      "fantasy",
      "valentine",
      "halloween",
    ],
    darkTheme: "dark",
    base: true,
    styled: true,
    utils: true,
    prefix: "",
    logs: false,
  },
};
